### ISSUE TITLE
NameError in README Simple Example

### ISSUE THREAD

**Issue by swamp09** [tamashii-io/tamashii-client#1]
I tried using tamashii-client. However, in Simple Example of README an error occurred.

https://github.com/swamp09/tamashii_client_example

``` ruby
> ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
> ruby client.rb  
/Users/numata/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tamashii-common-0.1.6/lib/tamashii/config.rb:25:in `ini
tialize': uninitialized constant Tamashii::Config::Set (NameError)
        from /Users/numata/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tamashii-common-0.1.6/lib/tamashii/config.
rb:11:in `new'
        from /Users/numata/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tamashii-common-0.1.6/lib/tamashii/config.
rb:11:in `method_missing'
        from client.rb:6:in `block in <main>'
        from /Users/numata/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tamashii-client-0.1.2/lib/tamashii/client.
rb:10:in `class_eval'
        from /Users/numata/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/tamashii-client-0.1.2/lib/tamashii/client.
rb:10:in `config'
        from client.rb:4:in `<main>'
```

I would appreciate it if you would give me some advice.

**Comment by elct9620** [comment]
Hi, @swamp09 

I want to know how you install your ruby.
Your problem seems your standard library [`Set`](http://ruby-doc.org/stdlib-2.4.2/libdoc/set/rdoc/Set.html) didn't exist.

**Comment by swamp09** [comment]
Sorry for the late reply.

I installed it using rbenv.

Adding `require 'Set'` to the beginning of the program worked fine.

**Comment by elct9620** [comment]
Great, I will close this issue.

We are rewriting this gem and will not use `Set` in next release, it can fix this issue too.
